// ─── Karakavak'ın insanları ───────────────────────────────────────────────
// vesikalık: web-src/portraits/<anahtar>.webp · pos/neg: gönlü olunca / kırılınca tepki
const PEOPLE = {
  fikret:   { ad: "Fikret", unvan: "Makam Şefi" },
  muhtar:   { ad: "Muhtar Rıza", unvan: "Kavaklı Mahallesi Muhtarı", pos: ["Mahalle sizi bağrına basar.", "Kavaklı bunu unutmaz başkanım."], neg: ["Kahvede anlatırım bunu.", "Kırk yıllık hatırın yok mu?"] },
  bekir:    { ad: "Hacı Bekir", unvan: "Esnaf ve Sanatkârlar Odası Başkanı", pos: ["Esnaf bunu unutmaz!", "Bereketli olsun başkanım."], neg: ["Esnaf da bunu unutmaz.", "Çarşıda konuşulur bu."] },
  huseyin:  { ad: "Çaycı Hüseyin", unvan: "Belediye Çay Ocağı", pos: ["Çaylar benden başkanım!", "Semaver sizin için kaynar."], neg: ["Çaylar bir süre açık gelir.", "Anlaşıldı başkanım..."] },
  kaymakam: { ad: "Selim Bey", unvan: "Karakavak Kaymakamı", pos: ["Uyumlu çalışmamız memnuniyet verici.", "Valiliğe olumlu rapor geçerim."], neg: ["Tutanağa geçmiştir.", "Üst makamlara bilgi vereceğim."] },
  vekil:    { ad: "Suat Bey", unvan: "Milletvekili, Ankara'dan", pos: ["Ankara'ya iyi haberler götürürüm.", "Sizi yukarıya övdüm başkanım."], neg: ["Ankara'ya iletirim.", "Bunu genel merkez duyar."] },
  nermin:   { ad: "Nermin Hanım", unvan: "Meclis Üyesi, Muhalefet", pos: ["Bak bu olmuş başkanım!", "Nadiren aynı fikirdeyiz."], neg: ["Meclise taşıyacağım.", "Tutanağa yazdırıyorum."] },
  hayri:    { ad: "Hayri Hoca", unvan: "Merkez Camii İmamı", pos: ["Allah razı olsun başkanım.", "Cemaat dua ediyor."], neg: ["Hayırlısı diyelim.", "Allah hayırlı eylesin..."] },
  burak:    { ad: "Burak", unvan: "Yeğeniniz, İçerik Üreticisi", pos: ["Efsane başkanım!", "Bunu hikâyeye atıyorum!"], neg: ["Cringe ya...", "Takipten çıkıyorum."] },
  albay:    { ad: "Nuri Bey", unvan: "Emekli Albay", pos: ["Yaşa! Var ol başkanım!", "Nizam intizam, işte bu."], neg: ["Böyle askerlik görmedim.", "Hiç yakışmadı."] },
  kemal:    { ad: "Kemal Bey", unvan: "Fen İşleri Müdürü", pos: ["Ekip hemen sahada!", "Kepçeler çalışsın!"], neg: ["Ekip bekler o zaman.", "Siz bilirsiniz başkanım."] },
  sevim:    { ad: "Sevim Hanım", unvan: "Mali Hizmetler Müdürü", pos: ["Hesaplar tuttu başkanım.", "Kuruşu kuruşuna."], neg: ["Hesap vermesi size kalsın.", "Not aldım başkanım."] },
  recep:    { ad: "Recep Amir", unvan: "Zabıta Amiri", pos: ["Emredersiniz başkanım!", "Ekip yola çıkıyor."], neg: ["Emir demiri keser...", "Peki başkanım."] },
  mahir:    { ad: "Komiser Mahir", unvan: "İlçe Emniyet Müdürü" },
  tuncay:   { ad: "Tuncay", unvan: "Karakavak Postası İmtiyaz Sahibi", pos: ["Yarınki manşete bakın!", "Kalemim sizden yana."], neg: ["Bunu da yazarım.", "Arşivime not düştüm."] },
  elif:     { ad: "Elif Öğretmen", unvan: "Cumhuriyet İlkokulu", pos: ["Çocuklar çok sevinecek!", "Teşekkürler başkanım."], neg: ["Çocuklara nasıl anlatacağım?", "Üzüldüm doğrusu."] },
  dursun:   { ad: "Dursun Ağa", unvan: "Çiftçi, Tarım Kooperatifi", pos: ["Toprak bereketli olsun!", "Köylü sizi unutmaz."], neg: ["Köylünün hâlini bilen yok.", "Tarla kurusun o zaman."] },
  cengiz:   { ad: "Cengiz Bey", unvan: "Müteahhit, Cengiz İnşaat", pos: ["İşte vizyon başkanım!", "Beton geleceğimizdir."], neg: ["Başka ilçeler de var.", "Pişman olursunuz."] },
  hatice:   { ad: "Hatice Abla", unvan: "Kadın Kooperatifi Başkanı", pos: ["Kadınlar size dua ediyor.", "Eliniz dert görmesin."], neg: ["Kadınları yine unuttunuz.", "Biz de kendi yolumuza."] },
  deniz:    { ad: "Deniz", unvan: "Üniversite Öğrencisi", pos: ["Gençlik sizinle!", "Harikasınız!"], neg: ["Gençlere yine yer yok.", "Bu ilçeden gideceğim."] },
  selin:    { ad: "Veteriner Selin", unvan: "Pati Derneği", pos: ["Patililer adına teşekkürler!", "Hav hav! (Yani sağ olun.)"], neg: ["Hayvanlar oy vermiyor diye mi?", "Çok üzüldüm."] },
  kaan:     { ad: "Kaan Bey", unvan: "Yatırımcı, İstanbul'dan", pos: ["Harika bir sinerji!", "Win-win başkanım."], neg: ["Yatırımcı küstü.", "Fırsatı kaçırdınız."] },
  naciye:   { ad: "Naciye Hanım", unvan: "Kayınvalideniz", pos: ["Aslan evladım benim!", "Bayramda dolma sizde."], neg: ["Dolma yok, bilesin.", "Bir anne kalbi kırıldı."] },
  ferhat:   { ad: "Ferhat Usta", unvan: "Oto Sanayi Sitesi", pos: ["Eyvallah başkanım!", "Sanayi sizindir."], neg: ["Yağ çekmedik diye mi?", "Anladım usta... başkanım."] },
  hans:     { ad: "Hans Bey", unvan: "Emekli, Almanya'dan", pos: ["Wunderbar!", "Sehr gut, Sayın Başkan!"], neg: ["Schade...", "Ach, çok yazık."] },
  orhan:    { ad: "Orhan Hoca", unvan: "Karakavakspor Kulüp Başkanı", pos: ["Tribünler sizi alkışlıyor!", "Şampiyonluk sizindir!"], neg: ["Taraftar bunu affetmez.", "Kırmızı kart başkanım."] },
  levent:   { ad: "Levent Bey", unvan: "Çimento Fabrikası Müdürü", pos: ["Üretim sürüyor!", "Yönetim kurulu memnun."], neg: ["Yönetim kurulu memnun olmayacak.", "Taşınmayı düşünürüz."] },
  tekir:    { ad: "Tekir", unvan: "Belediye Kedisi", pos: ["Mırrr."], neg: ["Tısss!"] },
  fatma:    { ad: "Fatma Teyze", unvan: "Vatandaş", pos: ["Allah ne muradın varsa versin!", "Kurban olayım size."], neg: ["Oyumu geri alıyorum.", "Hiç yakıştıramadım."] },
  rahmi:    { ad: "Kahveci Rahmi", unvan: "Yetmiş Yıllık Kıraathane", pos: ["Çayınız her zaman bizden!", "Dedeniz gibisiniz."], neg: ["Dedeniz böyle yapmazdı.", "Okey masası sizi konuşur."] },
  ayse:     { ad: "Ayşe", unvan: "Çocuk Başkan, 9 yaşında", pos: ["Yaşasııın!"], neg: ["Hiç adil değil!"] },
  ingrid:   { ad: "Ingrid Hanım", unvan: "Kardeş Şehir Heyeti, Norveç" },
};

// ─── Başkanlık vesikalıkları: başlıkta seçilir, her birinin kendi adı var ────
// Oyuncu kendi adını yazmazsa bu ad kullanılır. Eski başkanlar duvarı da bu resimleri asar.
// lakap + bio: seçim ekranındaki broşür. Gerçek kişi ya da parti yok; hepsi yerel siyasetin bilinen halleri.
const BASKANLAR = {
  "baskan-01": { ad: "Aslı Kavaklıoğlu", lakap: "Kurdele Aslı", bio: "Aynı çeşmenin üç ayrı açılışında da kurdeleyi o kesti. Makası çantasından çıkmaz: düğünde, sünnette, bir keresinde de dalgınlıkla bir cenazede." },
  "baskan-02": { ad: "Mehmet Emin Yurtsever", lakap: "Müjdeci Emin", bio: "On iki yılda Karakavak'a yedi fabrika müjdeledi. Arsa hep aynı, temel üç kez atıldı. Fabrika gelmedi ama müjdeler istihdam yarattı: iki basın danışmanı." },
  "baskan-03": { ad: "Gülten Arıkan", lakap: "Kasayı Boş Bulan", bio: "Apartman yöneticiliği, okul aile birliği, kooperatif... Nereye seçildiyse ilk iş 'kasayı boş bulduk' basın toplantısı yaptı. Kasalar sonra hep bankada çıktı." },
  "baskan-04": { ad: "Onur Kalaycı", lakap: "Ağır Çekim Onur", bio: "Kampanyası 212 videodan oluşuyor; hepsinde dizi müziği eşliğinde ağır çekim yürüyor. Kar yağınca eline kürek alır, kamera kapanınca küreği aldığı yere bırakır." },
  "baskan-05": { ad: "Cemal Kuzucu", lakap: "Asfalt Cemal", bio: "Seçimden önceki gece bütün mahalleyi asfaltladı, park etmiş arabaların etrafından dolanarak. Kavaklı'daki araba biçimli üç çukura muhtar 'Cemal'in eserleri' der." },
  "baskan-06": { ad: "Nesrin Ulusoy", lakap: "Rengârenk Nesrin", bio: "Otuz yılda dört parti değiştirdi, her seferinde çöp kutularını yeni partinin rengine boyattı. Karakavak'ın çöp kutularında dokuz kat boya var. 'Hizmetin rengi olmaz.'" },
  "baskan-07": { ad: "Saadet Kocabaş", lakap: "Ebedi Aday", bio: "1987'den beri her seçime girdi, on dokuzunu kaybetti. Bu sefer umutlu: rahmetli eşi hâlâ seçmen kütüğünde ve mezarlıktaki komşularını da ikna etmiş." },
  "baskan-08": { ad: "Hülya Kavuncu", lakap: "Dev Kavun Hülya", bio: "Festival derneğindeyken ilçe girişine 7 metrelik kavun heykeli diktirdi. Komşu ilçe 8 metrelik karpuz dikince ikinci kavunu çevre yoluna koydurdu. 'Kent estetiğine katkı.'" },
  "baskan-09": { ad: "Rüstem Aksakal", lakap: "Saat Kulesi Rüstem", bio: "Meydana dört yüzlü saat kulesi yaptırdı, her yüzü başka saati gösterir. Gerekçesi: 'Çoğu memlekette var, bizde de olsun.' Randevular o günden beri kuzey yüzüne göre verilir." },
  "baskan-10": { ad: "Nilgün Sarıbaş", lakap: "Kardeş Şehir Nilgün", bio: "Karakavak'a on bir kardeş şehir buldu, her birine meclisle birlikte 'niyet anlaşması' imzalamaya gitti. Norveç'ten geriye bir ren geyiği heykeli ve bir fatura kaldı." },
  "baskan-11": { ad: "Hikmet Çınaroğlu", lakap: "Borç Yadigârı", bio: "Otuz yıl belediye muhasebesinde çalıştı; SGK borcunu üç başkandan devraldı, dördüncüye bırakmayı planlıyor. Makam aracı haczedilince otobüse bindi, halk tevazu sandı." },
  "baskan-12": { ad: "Leman Tuncel", lakap: "Taziye Leman", bio: "Beş yılda ilçedeki 412 taziyenin 412'sine gitti, helvayı herkesten önce karıştırdı. Seçim bitince cenazeleri bıraktı; mahallede 'Leman Hanım'ı görmek için ölmek lazım' denir." },
  "baskan-13": { ad: "Pınar Ekinci", lakap: "Rekortmen Pınar", bio: "'Dünyanın en büyük kavun reçeli' rekor denemesini o yönetti. Kazan tartılırken ayağı kırıldı, rekor onaylanmadı. Reçel hâlâ belediye deposunda, Guinness'ten cevap bekliyor." },
  "baskan-14": { ad: "Derya Başaran", lakap: "Liman Derya", bio: "Denize 400 kilometre uzak Karakavak'a liman sözü verdi. İki etaplı bir planı var: önce deniz, sonra liman. Birinci etabın temeli iki kez atıldı." },
  "baskan-15": { ad: "Tolga Bıyıklı", lakap: "Soy Ağacı Tolga", bio: "Dernek başkanlığında teşkilat şemasını soy ağacıyla karıştırdı: damadı özel kalem, eniştesi basın müşaviri, halasının kedisi moral danışmanı. Tekir buna hâlâ içerliyor." },
  "baskan-16": { ad: "Zehra Tarlacı", lakap: "Anons Zehra", bio: "Yirmi yıl mahalle hoparlöründen 'Duyduk duymadık demeyin, dört ayaklı bir köpek kaybolmuştur' diye anons yaptı. Sesini herkes tanır; yüzünü ilk kez seçim afişinde gördüler." },
};

// ─── Evraklar ─────────────────────────────────────────────────────────────
// e: [halk, kasa, esnaf, ankara]
// chain: yalnız zincirle gelir · once: bir kez · cd: bekleme (ay) · w: ağırlık
// months: takvim ayı (0 = Ocak) · pre: seçim öncesi · req/not: bayrak · reqPol: yürürlükteki karar
// relMin/relMax: {kişi: eşik} · fav: gönderenin istediği taraf (varsayılan R) · norel: ilişkiye dokunmaz
// alt: [{req, text}] duruma göre metin
// seçenek: set/clr bayrak · inc sayaç · next: [kart, kaç ay sonra] · rel: {kişi: ±n}
//          pol: {id, ad, e (her ay), ay (süre; yoksa süresiz), done (bitişte), msg, doneCard} · cut: kaldırılan karar
const CARDS = [
  // ── Muhtar Rıza
  { id: "asfalt", who: "muhtar", konu: "Yol talebi", once: true,
    text: "Başkanım, Kavaklı'nın yolları köstebek yuvasına döndü. Seçimde asfalt sözü vermiştiniz, mahalle unutmadı.",
    L: { t: "Bütçe yok, sabır", e: [-10, 0, 0, 0], next: ["asfaltL", 4] },
    R: { t: "Asfaltı dökün", e: [10, -12, 5, 0], next: ["asfalt2", 3] } },
  { id: "asfaltL", who: "muhtar", konu: "Mahalle tepkisi", chain: true,
    text: "Mahalleli yolu kendi imkânıyla kazıp çakıl döktü başkanım. Şimdi çamur deryası; bir de köşeye 'BELEDİYE YOK' pankartı astılar.",
    L: { t: "Pankartı indirin", e: [-8, 0, 0, 3] },
    R: { t: "Asfalt ekibi yola", e: [8, -12, 3, 0] } },
  { id: "asfalt2", who: "kemal", konu: "Asfalt çalışması", chain: true, norel: true,
    text: "Kavaklı'ya asfaltı döktük başkanım. Ertesi sabah doğalgaz ekibi gelip yolu yeniden kazdı. Kimse kimseye haber vermemiş.",
    L: { t: "Doğalgazcı ödesin", e: [0, 6, 0, -8] },
    R: { t: "Bir daha dökün", e: [5, -10, 0, 0] } },
  { id: "kacakkat", who: "recep", konu: "Kaçak yapı", once: true,
    text: "Başkanım, Muhtar Rıza'nın evine gece gece kaçak kat çıkılmış. Tuğlalar hâlâ sıcak. Yıkalım mı?",
    L: { t: "Görmezden gel", e: [-6, 0, 0, -6], rel: { muhtar: 1 }, next: ["kacakfurya", 5] },
    R: { t: "Kanun herkese", e: [8, 0, 0, 6], rel: { muhtar: -2 }, next: ["muhtarkizgin", 3] } },
  { id: "kacakfurya", who: "recep", konu: "Kaçak yapı furyası", chain: true,
    text: "Muhtarın kaçak katını görmezden gelince bütün mahalle kat çıktı başkanım. Kavaklı'da tek katlı ev kalmadı.",
    L: { t: "İmar affı çıkaralım", e: [6, 6, 0, -12] },
    R: { t: "Hepsi yıkılsın", e: [-15, -5, 0, 10], rel: { muhtar: -1 } } },
  { id: "muhtarkizgin", who: "muhtar", konu: "Serzeniş", chain: true, fav: "L",
    text: "Kırk yıllık dostluk bir kat için mi bitti başkanım? Kahvede 'başkan beni yıktı' diyorum, bilesiniz.",
    L: { t: "Gel bir çayımı iç", e: [4, 0, 0, 0] },
    R: { t: "Kanun kanundur", e: [-6, 0, 0, 5] } },
  { id: "park", who: "muhtar", konu: "Çocuk parkı",
    text: "Mahallede çocuk parkı yok. Çocuklar inşaat kumunda oynuyor, akşam eve çimento gibi dönüyorlar.",
    L: { t: "Seneye bakarız", e: [-8, 0, 0, 0] },
    R: { t: "Park yapılsın", e: [4, -4, 0, 0], pol: { id: "park", ad: "Park inşaatı", e: [0, -1, 0, 0], ay: 4, done: [8, 0, 0, 0], msg: "Kavaklı parkı açıldı; çocuklar çimentodan kurtuldu." } } },
  { id: "muhtar_dost", who: "muhtar", konu: "İmece", relMin: { muhtar: 2 }, cd: 30, w: 2,
    text: "Başkanım, mahalle sizin için imece yaptı; parkın çitini kendimiz çektik. Bir çay ocağı açsak yeter bize.",
    L: { t: "Madalya takalım", e: [5, 0, 0, 2] },
    R: { t: "Ocak açılsın", e: [8, -3, 2, 0] } },
  { id: "muhtar_kus", who: "muhtar", konu: "Mahalle kararı", relMax: { muhtar: -2 }, cd: 30, w: 2, norel: true,
    text: "Başkanım, Kavaklı'da adınız artık geçmiyor. Seçimde bizden oy yok, baştan söyleyeyim de sonra şaşırmayın.",
    L: { t: "Oy halkın hakkı", e: [-6, 0, 0, 0], rel: { muhtar: -1 } },
    R: { t: "Mahalleye ziyaret", e: [5, -4, 0, 0], rel: { muhtar: 2 } } },

  // ── Hacı Bekir ve çarşı
  { id: "carsisus", who: "bekir", konu: "Bayram hazırlığı",
    text: "Bayram öncesi çarşıyı süsleyelim başkanım. Belediye ışıklandırsın, biz de indirim yapalım; bereket gelsin.",
    L: { t: "Süsü esnaf yapsın", e: [0, 3, -8, 0] },
    R: { t: "Çarşı ışıl ışıl", e: [4, -8, 10, 0] } },
  { id: "otopark", who: "bekir", konu: "Otopark",
    text: "Çarşıya otopark lazım başkanım. Müşteri park yeri bulamayınca komşu ilçeye gidiyor, kasap Ramazan ağlıyor.",
    L: { t: "Çarşı yayalaşsın", e: [6, -3, -14, 0] },
    R: { t: "Parkı otopark yapın", e: [-14, -3, 14, 0] } },
  { id: "halkekmek", who: "bekir", konu: "Halk Ekmek büfesi", fav: "L",
    text: "Halk Ekmek büfesi açacakmışsınız. Fırıncılar ayakta başkanım, 'belediye bize rakip mi oldu' diyorlar.",
    L: { t: "Vazgeçtik", e: [-6, 0, 10, 0] },
    R: { t: "Ekmek ucuzlasın", e: [12, -3, -12, 0], pol: { id: "halkekmek", ad: "Halk Ekmek büfesi", e: [0, -1, 0, 0], ay: 18 } } },
  { id: "pazaryeri", who: "bekir", konu: "Pazar günü",
    text: "Semt pazarı salıdan cumartesiye alınsın başkanım. Köylü de gelir, memur da gelir, bereket olur.",
    L: { t: "Salı kalsın", e: [-3, 0, -8, 0] },
    R: { t: "Cumartesi olsun", e: [5, 0, 10, -4] } },
  { id: "tabela", who: "bekir", konu: "Tabela yönetmeliği",
    text: "Zabıta 'tabelanız büyük' diye ceza yazmış. Dükkânın adı 'Meşhur Hacı Bekir Kebap, Lahmacun ve Künefe Salonu'. Küçük tabelaya sığmaz ki!",
    L: { t: "Yönetmelik yönetmeliktir", e: [4, 6, -10, 0], rel: { recep: 1 } },
    R: { t: "Cezaları silin", e: [-5, -5, 10, 0], rel: { recep: -1 } } },
  { id: "zincir", who: "bekir", konu: "Market ruhsatları",
    text: "Çarşıya üç zincir market açıldı, mahalle bakkalı kalmadı başkanım. Yeni ruhsatları durdurun!",
    L: { t: "Serbest rekabet", e: [6, 6, -14, 0] },
    R: { t: "Ruhsatlar durdurulsun", e: [-6, -5, 12, 0] } },
  { id: "schnitzel", who: "bekir", konu: "Turist akını", chain: true, fav: "L",
    text: "Turistler geldi başkanım. Kebapçı menüye 'şınitzel' yazdı, kahveci tavlanın yanına satranç koydu. Halk huzursuz.",
    L: { t: "Tabelalar Türkçe", e: [10, 0, -8, 0] },
    R: { t: "Para paradır", e: [-10, 8, 8, 0] } },
  { id: "harc", who: "bekir", konu: "İşgaliye harcı",
    text: "Esnaf zor durumda başkanım. Belediye işgaliye harcını bir yıl dondursun, bayramda dualarımız sizinle.",
    L: { t: "Harç harçtır", e: [0, 8, -10, 0] },
    R: { t: "Dondurun", e: [0, -3, 8, 0], pol: { id: "harc", ad: "Harç dondurma", e: [0, -1, 0, 0], ay: 12 } } },
  { id: "bekir_dost", who: "bekir", konu: "Esnaftan jest", relMin: { bekir: 2 }, cd: 30, w: 2,
    text: "Esnaf kendi arasında para topladı başkanım; belediyeye bağış yapmak istiyoruz. Tek ricamız çarşıya bir çeşme.",
    L: { t: "Bağış kasaya", e: [0, 12, 3, 0] },
    R: { t: "Çeşmeyi biz yapalım", e: [5, -3, 8, 0] } },
  { id: "bekir_kus", who: "recep", konu: "İmza kampanyası", relMax: { bekir: -2 }, cd: 30, w: 2, norel: true,
    text: "Hacı Bekir çarşıda imza topluyor başkanım: 'Başkan esnafı sattı.' Kasap Ramazan iki kere imzalamış.",
    L: { t: "İmzalar ne olacak", e: [-3, 0, -12, 0], rel: { bekir: -1 } },
    R: { t: "Hacı Bekir'e ziyaret", e: [0, -4, 8, 0], rel: { bekir: 2 } } },

  // ── Çaycı Hüseyin
  { id: "cayzam", who: "huseyin", konu: "Çay ocağı",
    text: "Başkanım, çay beş lira, şeker bedava, bardak benden. Bu gidişle ocağı söndüreceğim.",
    L: { t: "Çay halkın hakkı", e: [6, -5, 0, 0] },
    R: { t: "Zam yap", e: [-6, 5, 5, 0] } },
  { id: "semaver", who: "huseyin", konu: "Demirbaş talebi",
    text: "Semaver yirmi yıllık, dün gece patladı. Meclis toplantısı çaysız geçerse mesuliyet kabul etmem.",
    L: { t: "Termos kullan", e: [-4, 4, 0, 0] },
    R: { t: "Yeni semaver", e: [4, -6, 4, 0] } },
  { id: "huseyin_dost", who: "huseyin", konu: "Özel harman", relMin: { huseyin: 2 }, cd: 30, w: 2,
    text: "Başkanım, size özel bir harman yaptım: 'Başkanın Harmanı'. Paketleyip satsak çarşıda kapışılır.",
    L: { t: "Meclise ikram", e: [4, 0, 0, 3] },
    R: { t: "Satışa çıkaralım", e: [3, 8, 4, 0] } },
  { id: "huseyin_kus", who: "huseyin", konu: "Poşet çay", relMax: { huseyin: -2 }, cd: 30, w: 2, fav: "R",
    text: "Başkanım, artık demlemiyorum, poşet çay veriyorum. Kırgınım. Meclis üyeleri de fark etti.",
    L: { t: "Poşet de çaydır", e: [-4, 0, 0, -3] },
    R: { t: "Hüseyin, gel otur", e: [0, -2, 0, 0], rel: { huseyin: 1 } } },

  // ── Kaymakam Selim Bey
  { id: "tatbikat", who: "kaymakam", konu: "Deprem tatbikatı",
    text: "AFAD ile deprem tatbikatı yapacağız başkanım. Belediye binası da boşaltılacak, meclis dâhil.",
    L: { t: "İşimiz başımızdan aşkın", e: [-5, 0, 0, -10] },
    R: { t: "Tatbikat şart", e: [5, -3, 0, 8] } },
  { id: "piknik", who: "kaymakam", konu: "Yangın sezonu", months: [5, 6, 7], w: 2,
    text: "Orman yangını riski yüksek. Ormanlık alanda mangal ve piknik yasağı ilan etsek?",
    L: { t: "Mangal halkın hakkı", e: [8, 0, 3, -12] },
    R: { t: "Yasak ilan edilsin", e: [-8, 0, -4, 10] } },
  { id: "bayrak", who: "kaymakam", konu: "Bayram hazırlığı",
    text: "Bayramda bütün resmî binalar donatılacak. Belediyenin bayrak direği paslanmış, bayrak da solmuş.",
    L: { t: "İdare eder", e: [-3, 0, 0, -10] },
    R: { t: "Yeni direk, yeni bayrak", e: [5, -6, 0, 8] } },
  { id: "genelge", who: "kaymakam", konu: "Genelge",
    text: "Ankara'dan genelge geldi: bütün belediye tabelaları kurumsal renge boyanacak. Masrafı belediyelerden.",
    L: { t: "Boya yok", e: [0, 0, 0, -12] },
    R: { t: "Boyayın", e: [-3, -8, 0, 10] } },
  { id: "kardes", who: "kaymakam", konu: "Kardeş şehir", once: true,
    text: "Norveç'ten bir kasaba Karakavak'la kardeş şehir olmak istiyor. Heyetleri gelecek ay geliyor.",
    L: { t: "Neyimize lazım", e: [0, 0, 0, -5] },
    R: { t: "Hoş gelsinler", e: [5, -6, 3, 5], next: ["norvec", 1] } },
  { id: "mozaik", who: "kaymakam", konu: "Arkeolojik buluntu", once: true,
    text: "Çarşıdaki kanalizasyon kazısında Roma dönemi mozaik çıktı! Müze Müdürlüğü inşaatı durdurdu.",
    L: { t: "Üstünü örtün", e: [0, 5, 6, -15] },
    R: { t: "Kazı sürsün", e: [5, -4, -4, 10], pol: { id: "kazi", ad: "Arkeolojik kazı", e: [0, 0, -1, 0], ay: 5, doneCard: "mozaik2", msg: "Kazı bitti, mozaik gün yüzüne çıktı!" } } },

  // ── Milletvekili Suat Bey
  { id: "kadro", who: "vekil", konu: "İstihdam ricası",
    text: "Başkanım, bizim hemşerinin oğlu var, çok akıllı çocuk. Belediyede bir kadro... Anlarsınız.",
    L: { t: "Liyakat esastır", e: [6, 0, 0, -14] },
    R: { t: "Bir yer buluruz", e: [-10, -3, 0, 14], pol: { id: "kadro", ad: "Torpilli kadro maaşı", e: [0, -1, 0, 0], ay: 10 } } },
  { id: "bakan", who: "vekil", konu: "Bakan ziyareti",
    text: "Bakan Bey ilçeye geliyor! Yol boyu pankart, meydanda çiçek, kırmızı halı. Belediye hazırlasın.",
    L: { t: "Sade karşılayalım", e: [5, 0, 0, -12] },
    R: { t: "Kırmızı halı!", e: [-5, -14, 5, 15] } },
  { id: "konut", who: "vekil", konu: "Sosyal konut", once: true,
    text: "Ankara 500 konutluk sosyal konut projesi veriyor. Tek şart: arsa belediyeden. Mera var ya, o olur.",
    L: { t: "Mera gitmez", e: [5, 0, -3, -15], rel: { dursun: 1 } },
    R: { t: "Arsayı verelim", e: [-5, -8, 6, 14], rel: { dursun: -1 }, pol: { id: "konut", ad: "Sosyal konut inşaatı", e: [0, 0, 1, 0], ay: 8, done: [10, 0, 0, 4], msg: "Sosyal konutlar teslim edildi; 500 aile anahtarını aldı." } } },
  { id: "odul", who: "vekil", konu: "Ödül töreni", months: [6, 7], cd: 12,
    text: "Ankara size 'Örnek Belediye' ödülü verecek! Tören Ankara'da, aynı gün de Kavun Festivali var. Hangisi?",
    L: { t: "Festival bizim", e: [8, 0, 5, -12] },
    R: { t: "Ankara'ya gidiyorum", e: [-8, 0, -4, 12] } },
  { id: "millet", who: "vekil", konu: "Ankara projesi", once: true,
    text: "Ankara'nın 'Her İlçeye Bir Bahçe' projesi var. Parası bizden değil; karşılığında açılışta uzun bir teşekkür konuşması.",
    L: { t: "Kendi bahçemiz var", e: [-4, 0, 0, -10] },
    R: { t: "Teşekkürler Ankara", e: [7, 3, 0, 10] } },
  { id: "miting", who: "vekil", konu: "Miting organizasyonu", pre: true, cd: 40,
    text: "Genel Başkan seçim öncesi mitinge geliyor. Meydanı doldurmak lazım, otobüsleri belediye ayarlasın.",
    L: { t: "Otobüsler halkın", e: [5, 0, 0, -15] },
    R: { t: "Otobüsler hazır", e: [-5, -12, 0, 15] } },
  { id: "vekil_dost", who: "vekil", konu: "Ek ödenek", relMin: { vekil: 2 }, cd: 30, w: 2,
    text: "Müjde başkanım: Ankara'dan ek ödenek çıktı! Tek şart, açılışa Bakan Bey'i davet etmeniz.",
    L: { t: "Ödenek yeter", e: [0, 10, 0, -3] },
    R: { t: "Bakan Bey de gelsin", e: [0, 12, 0, 6] } },
  { id: "vekil_kus", who: "kaymakam", konu: "Genelge yağmuru", relMax: { vekil: -2 }, cd: 30, w: 2, norel: true,
    text: "Suat Bey Ankara'da aleyhinize konuşuyormuş başkanım. Genelge üstüne genelge geliyor, denetçiler yolda.",
    L: { t: "Umurumda değil", e: [3, 0, 0, -12], rel: { vekil: -1 } },
    R: { t: "Ankara'ya gidin, barışın", e: [0, -5, 0, 10], rel: { vekil: 2 } } },

  // ── Nermin Hanım (muhalefet)
  { id: "koltuk", who: "nermin", konu: "Soru önergesi",
    text: "Makam odasına 80 bin liralık deri koltuk alınmış! Vatandaş tabure bulamazken bu ne israf?",
    L: { t: "Bel fıtığım var", e: [-10, 0, 0, 0] },
    R: { t: "Koltuk iade edilsin", e: [10, 3, 0, 0] } },
  { id: "canliyayin", who: "nermin", konu: "Şeffaflık önergesi", once: true,
    text: "Meclis toplantılarını canlı yayınlayalım. Vatandaş kimin ne dediğini, kimin uyuduğunu görsün.",
    L: { t: "Gerek yok", e: [-6, 0, 0, 5] },
    R: { t: "Yayına alın", e: [10, -3, 0, -5], next: ["horlama", 2] } },
  { id: "kres", who: "nermin", konu: "Ortak proje",
    text: "Bu sefer sizinle aynı fikirdeyim başkanım. Çalışan anneler için ücretsiz kreş açalım; imzamı atarım.",
    L: { t: "Muhalefetle iş olmaz", e: [-6, 0, 0, 5] },
    R: { t: "El sıkışalım", e: [10, -3, 0, -6], pol: { id: "kres", ad: "Ücretsiz kreş", e: [0, -1, 0, 0], ay: 12 } } },
  { id: "skandal", who: "nermin", konu: "İmar usulsüzlüğü", chain: true, fav: "L",
    text: "Dere yatağına 20 katlı bina diken müteahhide imar izni vermişsiniz. Belgeler bende başkanım.",
    L: { t: "İzin iptal", e: [10, -10, -5, 0], clr: "towers", rel: { cengiz: -2 } },
    R: { t: "Belgeler sahte", e: [-14, 0, 0, 5] } },
  { id: "torpil", who: "nermin", konu: "Torpil iddiası", chain: true,
    text: "Kayınvalidenizin sokağına bir günde lamba takılmış; benim mahallemde üç aydır zifiri karanlık! Torpil değil de ne?",
    L: { t: "Tesadüf", e: [-8, 0, 0, 0] },
    R: { t: "Bütün mahallelere lamba", e: [6, -8, 0, 0] } },
  { id: "nermin_dost", who: "nermin", konu: "Bütçe oylaması", relMin: { nermin: 2 }, cd: 30, w: 2,
    text: "Başkanım, bu yıl bütçeye muhalefet olarak 'evet' diyeceğiz. Siyasette nadir görülür, kıymetini bilin.",
    L: { t: "Sessiz geçelim", e: [2, 4, 0, 0] },
    R: { t: "Ortak basın açıklaması", e: [8, 4, 0, -5] } },
  { id: "nermin_kus", who: "nermin", konu: "Şikâyet dilekçesi", relMax: { nermin: -2 }, cd: 30, w: 2, fav: "R",
    text: "Hakkınızda Sayıştay'a şikâyet dilekçesi verdim başkanım. İmza atan meclis üyesi sayısı: dokuz.",
    L: { t: "Mahkemede görüşürüz", e: [-6, -6, 0, -3] },
    R: { t: "Oturup konuşalım", e: [0, 0, 0, 0], rel: { nermin: 1 } } },

  // ── Hayri Hoca
  { id: "hoparlor", who: "hayri", konu: "Ses sistemi",
    text: "Minarenin hoparlörü cızırdıyor; ezan radyo paraziti gibi çıkıyor. Belediye bir ses sistemi alsa?",
    L: { t: "Müftülüğe yazalım", e: [-5, 0, 0, 4] },
    R: { t: "Alalım", e: [6, -5, 0, 2] } },
  { id: "iftar", who: "hayri", konu: "İftar çadırı", cd: 12,
    text: "Ramazan geliyor başkanım. Meydana herkese açık bir iftar çadırı kuralım; yolcu, garip, öğrenci...",
    L: { t: "Kasa elvermez", e: [-10, 6, 0, 0] },
    R: { t: "Çadır kurulsun", e: [10, -10, 5, 3] } },
  { id: "yagmur", who: "hayri", konu: "Kuraklık", months: [5, 6, 7], w: 1.5,
    text: "Kuraklık var başkanım. Köylüler yağmur duasına çıkacak; belediye otobüs verirse tepeye kadar gideriz.",
    L: { t: "Önce su tasarrufu", e: [-6, 5, 0, 5] },
    R: { t: "Otobüs de verelim", e: [8, -5, 0, 0], rel: { dursun: 1 } } },
  { id: "hayri_dost", who: "hayri", konu: "Cuma vaazı", relMin: { hayri: 2 }, cd: 30, w: 2,
    text: "Cuma vaazında belediyenin hizmetlerini andım başkanım. Cemaat dua etti. Bir de Kuran kursuna bir oda versek?",
    L: { t: "Dua yeter hocam", e: [3, 0, 0, 0] },
    R: { t: "Oda verelim", e: [8, -3, 0, 2] } },

  // ── Yeğen Burak
  { id: "yegen", who: "burak", konu: "Sosyal medya", once: true,
    text: "Selam başkanım! Belediyenin sosyal medyasını ben yöneteyim. Ayda sadece 40 bin, aileye özel fiyat.",
    L: { t: "Aile işe karışmaz", e: [5, 0, 0, 0], next: ["yegenrakip", 10] },
    R: { t: "Başla bakalım", e: [-5, -4, 0, -5], set: "yegen", next: ["viral", 2], pol: { id: "yegen", ad: "Yeğenin maaşı", e: [0, -1, 0, 0], ay: 12 } } },
  { id: "yegenrakip", who: "burak", konu: "Aile içi şeffaflık", chain: true,
    text: "Başkanım, siz iş vermeyince rakip adayın sosyal medyasını yönetmeye başladım. Bilginiz olsun; aile içi şeffaflık.",
    L: { t: "Bayramda konuşuruz", e: [-6, 0, 0, 0] },
    R: { t: "Tamam, gel işe başla", e: [3, -8, 0, -3], set: "yegen" } },
  { id: "viral", who: "burak", konu: "Viral içerik", chain: true,
    text: "Müjde başkanım! 'Başkan açılışta kurdeleyle birlikte kendi kravatını da kesiyor' videomuz 2 milyon izlendi!",
    L: { t: "Sil hemen", e: [-5, 0, 0, 5] },
    R: { t: "Viral viraldir", e: [14, 0, 3, -10], next: ["reklam", 5] } },
  { id: "reklam", who: "burak", konu: "Marka iş birliği", chain: true,
    text: "Bir enerji içeceği makam odasında reklam çekmek istiyor. Siz sadece kameraya 'Başkanın enerjisi!' diyeceksiniz.",
    L: { t: "Makam satılık değil", e: [5, 0, 0, 5] },
    R: { t: "Kaç para?", e: [-8, 15, 0, -10] } },
  { id: "dijital", who: "burak", konu: "Yapay zekâ", req: ["yegen"], once: true, minM: 10,
    text: "Belediyeye yapay zekâ asistanı yapalım! Adını da 'Dijital Fikret' koyarız. (Fikret kapıdan size bakıyor.)",
    L: { t: "Bir Fikret yeter", e: [0, 0, 0, 0] },
    R: { t: "Dijital Fikret!", e: [6, -6, 0, 5], next: ["dijital2", 4] } },
  { id: "dijital2", who: "fikret", konu: "Dijital Fikret", chain: true,
    text: "Başkanım, Dijital Fikret vatandaşlara 'başkan şu an tavla oynuyor' demiş. Doğru ama söylenmez ki!",
    L: { t: "Fişini çekin", e: [-4, 4, 0, 0] },
    R: { t: "Güncelleme yapılsın", e: [4, -6, 0, 0] } },
  { id: "yilbasi", who: "burak", konu: "Yılbaşı etkinliği", months: [11], w: 2, cd: 12,
    text: "Yılbaşında meydana ışık gösterisi yapalım başkanım! Drone'larla gökyüzüne dev bir kavun çizeriz.",
    L: { t: "Sade kutlayalım", e: [-4, 5, -3, 0] },
    R: { t: "Işıklar yansın", e: [8, -10, 8, 0] } },

  // ── Emekli Albay Nuri Bey
  { id: "fener", who: "albay", konu: "29 Ekim", months: [9], w: 5, cd: 12,
    text: "Ah ah... Eskiden 29 Ekim'de fener alayı olurdu, bando çalardı, tüylerimiz diken diken olurdu. Bu sene bir fener alayı yapalım mı başkanım?",
    L: { t: "Kasa kısıtlı", e: [-6, 5, 0, -5] },
    R: { t: "Bando da gelsin!", e: [10, -8, 5, 5] } },
  { id: "mars", who: "albay", konu: "İlçe marşı", once: true,
    text: "İlçemizin bir marşı olmalı! Sözlerini ben yazdım: 'Karakavak, ey Karakavak, kavunun tatlı, suyun berrak...' Yalnız on dört kıta.",
    L: { t: "Kıtaları kısaltalım", e: [3, 0, 0, 0] },
    R: { t: "Okullarda okunsun", e: [-8, 0, 0, 6], rel: { elif: -1 } } },
  { id: "cadde", who: "albay", konu: "Cadde adı", once: true, fav: "L",
    text: "Yeni caddeye isim lazım başkanım. Ben ilçemizin ilk öğretmeni Şükrü Hoca diyorum. Yeğeniniz Burak ise 'TikTok Bulvarı' diyor.",
    L: { t: "Şükrü Hoca Caddesi", e: [6, 0, 0, 3], rel: { burak: -1 } },
    R: { t: "TikTok Bulvarı", e: [-6, 0, 4, -5], rel: { burak: 1 } } },

  // ── Fen İşleri Kemal Bey
  { id: "kar", who: "kemal", konu: "Kış hazırlığı", months: [11, 0, 1], w: 3, cd: 10,
    text: "Kar bastırdı başkanım, tuz stoğu bitti. Komşu ilçe tuzu altın fiyatına veriyor.",
    L: { t: "Kürekle açılsın", e: [-10, 0, -6, 0] },
    R: { t: "Tuzu alın", e: [5, -12, 5, 0] } },
  { id: "sel", who: "kemal", konu: "Altyapı", cd: 30,
    text: "Sağanak çarşıyı su bastı. Kanalizasyon 1970'den kalma, borular pamuk ipliğine bağlı.",
    L: { t: "Pompa getirin", e: [-4, -5, 5, 0] },
    R: { t: "Altyapı baştan", e: [0, -12, -6, 6], pol: { id: "altyapi", ad: "Altyapı inşaatı", e: [0, -1, -1, 0], ay: 5, done: [10, 0, 6, 0], msg: "Altyapı bitti; çarşıyı bir daha su basmaz." } } },
  { id: "cop", who: "kemal", konu: "Çöp kamyonu",
    text: "Tek çöp kamyonumuz yine bozuldu. Üç gündür çöp toplanmıyor, mahalle kedileri bayram ediyor.",
    alt: [{ req: "karaca", text: "Tek çöp kamyonumuz yine bozuldu. Eşek Karaca üç gündür bütün ilçenin çöpünü tek başına topluyor; gözlerinde bir sitem var." }],
    L: { t: "Tamir ettirin", e: [-6, -5, 0, 0] },
    R: { t: "Yeni kamyon", e: [10, -15, 0, 0] } },
  { id: "kopru", who: "kemal", konu: "Tarihî köprü", once: true,
    text: "Derenin üstündeki tarihî taş köprü çatladı. Restorasyon için Vakıflar'dan izin lazım, o da iki yıl sürer.",
    L: { t: "İzni bekleyin", e: [-6, 0, 0, 6] },
    R: { t: "Biz yaparız", e: [8, -10, 0, -10] } },
  { id: "towers2", who: "kemal", konu: "Zemin etüdü", req: ["towers"], once: true, minM: 8, fav: "L",
    text: "Başkanım, Karakavak Towers'ın temelinden su çıktı. Bina bir tarafa yatıyor gibi. Ben 'yatmıyor' demem.",
    L: { t: "Yıkın", e: [10, -15, -5, 0], clr: "towers", rel: { cengiz: -2 } },
    R: { t: "Pisa gibi turistik olur", e: [-10, 5, 10, -6] } },
  { id: "itfaiye", who: "kemal", konu: "İtfaiye aracı", req: ["towers"], once: true, minM: 6,
    text: "İtfaiyenin merdiveni ikinci kata kadar uzanıyor başkanım. Karakavak Towers yirmi kat. Yeni araç şart.",
    L: { t: "Dua edelim", e: [-8, 0, 0, -6] },
    R: { t: "Yeni itfaiye aracı", e: [8, -18, 0, 5] } },
  { id: "hurda", who: "kemal", konu: "Hurda araçlar", once: true, norel: true,
    text: "Depoda otuz yıllık hurda araçlar çürüyor. Satarsak iyi para eder. Yalnız biri 1974 model, ilçenin ilk itfaiye aracı.",
    L: { t: "Müze yapalım", e: [5, -4, 0, 0], rel: { albay: 1 } },
    R: { t: "Hepsi hurdacıya", e: [-4, 12, 0, 0], rel: { albay: -1 } } },
  { id: "gecegunduz", who: "kemal", konu: "Seçim çalışmaları", pre: true, cd: 40, w: 2,
    text: "Seçime az kaldı başkanım. Gece gündüz asfalt dökelim mi? Vatandaş taze asfaltın kokusunu sever.",
    L: { t: "Plan neyse o", e: [-6, 0, 0, 0] },
    R: { t: "Gece gündüz!", e: [15, -18, 5, 0] } },
  { id: "kemal_dost", who: "kemal", konu: "Müjde", relMin: { kemal: 2 }, cd: 30, w: 2,
    text: "Başkanım, hurda malzemeyle sanayi yolunu yaptık. Kasaya kuruş maliyeti yok; ekip gönüllü çalıştı.",
    L: { t: "Aferin Kemal", e: [3, 6, 6, 0] },
    R: { t: "Ekibe ikramiye", e: [2, -3, 6, 0], rel: { kemal: 1 } } },
  { id: "kemal_kus", who: "fikret", konu: "Fen İşleri", relMax: { kemal: -2 }, cd: 30, w: 2,
    text: "Başkanım, Fen İşleri işi ağırdan alıyor; Kemal Bey size kırgın. Çukurlar sırada, kepçeler çay molasında.",
    L: { t: "Soruşturma açın", e: [-4, 0, 0, 3], rel: { kemal: -1 }, pol: { id: "yavas", ad: "Fen İşleri ağırdan alıyor", e: [-1, 0, 0, 0], ay: 5 } },
    R: { t: "Kemal Bey'le çay", e: [0, 0, 0, 0], rel: { kemal: 2 } } },

  // ── Komiser Mahir
  { id: "trafik", who: "mahir", konu: "Trafik ışığı", fav: "L",
    text: "İlçenin tek trafik ışığı bozuldu. İşin ilginci, bir haftadır herkes birbirine yol veriyor; kaza sıfır.",
    L: { t: "Tamir edin", e: [0, -3, 0, 6] },
    R: { t: "Böyle kalsın", e: [6, 3, 0, -6] } },
  { id: "otogar", who: "mahir", konu: "ACİL", once: true, minM: 3, norel: true,
    text: "Başkanım, otogarda cinayet var! ...Yani vatandaş öyle diyor: kantinde tost 180 lira, çay 40 lira olmuş. Adam karakola gelip şikâyet etti.",
    L: { t: "Serbest piyasa", e: [-10, 0, 10, 0] },
    R: { t: "Fiyat tarifesi", e: [10, 0, -10, 0] } },
  { id: "minibus", who: "mahir", konu: "Toplu taşıma",
    text: "Minibüsçüler durakta değil, vatandaş nerede el ederse orada duruyor. Durak zorunluluğu getirelim mi?",
    L: { t: "Her yer durak", e: [6, 0, 5, -5] },
    R: { t: "Durak zorunlu", e: [-6, 0, -5, 6] } },

  // ── Mali Hizmetler Sevim Hanım
  { id: "butce", who: "sevim", konu: "Yıllık bütçe", months: [0], w: 8, cd: 11, fav: "L",
    text: "Yeni yılın bütçesi meclisten geçti, Ankara'dan pay da yattı başkanım. Artan parayı ne yapalım?",
    L: { t: "Kenara koyalım", e: [0, 14, 0, 0] },
    R: { t: "Mahallelere yatırım", e: [7, 5, 4, 0] } },
  { id: "sgk", who: "sevim", konu: "SGK borcu", once: true, norel: true,
    text: "SGK borcu kapıda başkanım. Ya yapılandıracağız ya da makam aracını satacağız.",
    L: { t: "Yapılandırın", e: [0, 0, 0, 5], pol: { id: "sgk", ad: "SGK taksiti", e: [0, -1, 0, 0], ay: 10 } },
    R: { t: "Makam aracı gitsin", e: [8, 12, 0, -5], set: "bisiklet", next: ["bisiklet", 2] } },
  { id: "maas", who: "sevim", konu: "Maaş ödemesi", cd: 24, norel: true,
    text: "Personel maaşları için kasada para kalmadı. Ya bankadan kredi çekeceğiz ya da maaşlar gecikecek.",
    L: { t: "Maaşlar gecikecek", e: [-15, 8, -4, 0] },
    R: { t: "Krediyi çekin", e: [0, 18, 0, -3], pol: { id: "kredi", ad: "Kredi taksiti", e: [0, -2, 0, 0], ay: 8 } } },
  { id: "elektrik", who: "sevim", konu: "Elektrik faturası", once: true, norel: true,
    text: "Sokak lambalarının faturası kasayı yakıyor. Gece yarısından sonra lambaları kıssak mı?",
    L: { t: "Lambaları kısın", e: [-10, 10, -4, 0] },
    R: { t: "Güneş paneli kuralım", e: [3, -12, 0, 5], pol: { id: "gunes", ad: "Güneş paneli kurulumu", e: [0, 0, 0, 0], ay: 8, doneCard: "gunes", msg: "Güneş panelleri devrede!" } } },
  { id: "gunes", who: "sevim", konu: "Enerji geliri", chain: true, norel: true,
    text: "Güneş panelleri ihtiyaçtan fazla üretiyor başkanım! Fazla elektriği satıyoruz. Otuz yıllık memuriyetimde ilk kez gülüyorum.",
    L: { t: "Gelir kasaya", e: [0, 4, 0, 0], pol: { id: "gunes2", ad: "Güneş enerjisi geliri", e: [0, 1, 0, 0], ay: 24 } },
    R: { t: "Faturalar düşsün", e: [12, 3, 0, 0] } },
  { id: "emlak", who: "sevim", konu: "Vergi tahsilatı",
    text: "Emlak vergisi tahsilatı çok düşük. İcra takibi başlatalım mı? Listenin başında... Hacı Bekir var.",
    L: { t: "Af çıkaralım", e: [8, -10, 6, 0], rel: { bekir: 1 } },
    R: { t: "Tahsilat başlasın", e: [-8, 15, -10, 0], rel: { bekir: -1 } } },
  { id: "kira", who: "sevim", konu: "Dükkân kiraları",
    text: "Belediyeye ait çarşı dükkânlarının kirası on yıldır aynı. Hacı Bekir ayda bir simit parası ödüyor. Güncelleyelim mi?",
    L: { t: "Esnafa dokunmayın", e: [0, -3, 7, 0], rel: { bekir: 1 } },
    R: { t: "Kiralar güncellensin", e: [0, 4, -10, 0], rel: { bekir: -1 }, pol: { id: "kira", ad: "Güncel dükkân kiraları", e: [0, 1, 0, 0] } } },
  { id: "kantin", who: "sevim", konu: "Kantin ihalesi", fav: "L",
    text: "Otogar kantininin kira süresi doldu. Yeni kiracıdan yüksek kira mı alalım, yoksa ucuz çay şartı mı koyalım?",
    L: { t: "Yüksek kira", e: [-6, 12, 0, 0] },
    R: { t: "Ucuz çay şartı", e: [8, -2, -4, 0] } },
  { id: "eskibina", who: "sevim", konu: "Taşınmaz satışı", once: true,
    text: "Belediyenin eski binası boş duruyor. Bir otel zinciri iyi para veriyor başkanım. Satalım mı?",
    L: { t: "Tarihimiz satılmaz", e: [5, -2, 0, 0], rel: { albay: 1 } },
    R: { t: "Satın gitsin", e: [-6, 18, 4, 0], rel: { albay: -1 } } },
  { id: "suzam", who: "sevim", konu: "Su tarifesi",
    text: "Suya zam yapmadan kasa dönmüyor başkanım. Barajdan eve kadar her damla para.",
    L: { t: "Suya zam olmaz", e: [5, -10, 0, 0] },
    R: { t: "Yüzde otuz zam", e: [-12, 6, -3, 0], pol: { id: "suzam", ad: "Su zammı geliri", e: [0, 1, 0, 0], ay: 15 } } },
  { id: "emekliiptal", who: "sevim", konu: "Ulaşım bütçesi", reqPol: "emekli", minM: 6, cd: 18,
    text: "Emekliye bedava otobüs kasayı yiyor başkanım. Ya kaldırırız ya da başka yerden keseriz.",
    L: { t: "Emekliye dokunmayın", e: [0, -3, 0, 0] },
    R: { t: "Uygulama kalksın", e: [-12, 4, 0, 0], cut: "emekli", rel: { fatma: -2 } } },
  { id: "sevim_dost", who: "sevim", konu: "Unutulmuş hesap", relMin: { sevim: 2 }, cd: 30, w: 2,
    text: "Başkanım, eski bir emanet hesabında unutulmuş para buldum! Hesaplar tertemiz, gönül rahatlığıyla kullanın.",
    L: { t: "Kasada kalsın", e: [0, 14, 0, 0] },
    R: { t: "Personele ikramiye", e: [6, 6, 0, 0] } },
  { id: "sevim_kus", who: "sevim", konu: "İstifa dilekçesi", relMax: { sevim: -2 }, cd: 30, w: 2,
    text: "Sevim Hanım istifa dilekçesini masanıza bıraktı: 'Bu belediyede hesap tutmak mümkün değil başkanım.'",
    L: { t: "İstifası kabul", e: [0, -6, 0, -4], pol: { id: "malikaos", ad: "Mali işler karışık", e: [0, -1, 0, 0], ay: 6 } },
    R: { t: "Gönlünü alın", e: [0, -4, 0, 0], rel: { sevim: 2 } } },

  // ── Zabıta Recep Amir ve kıraathane
  { id: "seyyar", who: "recep", konu: "Seyyar satıcılar",
    text: "Pazar kaldırımlarını seyyar satıcılar kapattı, bebek arabası geçmiyor. Kaldıralım mı başkanım?",
    L: { t: "Ekmek parası, kalsın", e: [5, 0, -10, 0], rel: { bekir: -1 } },
    R: { t: "Kaldırım yayanındır", e: [-8, 0, 10, 0], rel: { bekir: 1 } } },
  { id: "kurban", who: "recep", konu: "Kurban satış yeri", cd: 12, norel: true,
    text: "Kurban satış yeri nereye kurulsun? Geçen sene keçiler belediye bahçesindeki gülleri yedi.",
    L: { t: "İlçe dışına", e: [-5, 0, -5, 5] },
    R: { t: "Pazar yerine", e: [5, 0, 6, -5] } },
  { id: "otoparkucret", who: "recep", konu: "Otopark ücreti",
    text: "Çarşı otoparkına ücret koyalım mı başkanım? Herkes arabasını sabah bırakıp akşam alıyor, müşteriye yer kalmıyor.",
    L: { t: "Ücretsiz kalsın", e: [5, -3, -5, 0] },
    R: { t: "Saatlik ücret", e: [-6, 3, 5, 0], pol: { id: "otoparkucret", ad: "Otopark geliri", e: [0, 1, 0, 0], ay: 20 } } },
  { id: "kiraathane", who: "rahmi", konu: "Kaldırım işgali",
    text: "Zabıta kaldırıma masa attık diye ceza yazıyor. Bu kıraathane yetmiş yıllık başkanım; dedeniz burada okey oynardı!",
    L: { t: "Kural kuraldır", e: [-5, 5, -10, 0], rel: { recep: 1 } },
    R: { t: "Masalar kalsın", e: [5, 0, 10, -4], rel: { recep: -1 } } },
  { id: "okey", who: "rahmi", konu: "Turnuva", once: true,
    text: "Belediye Okey Kupası düzenleyelim başkanım! Bütün kıraathaneler katılır, kazanana altın kaplama taş.",
    L: { t: "Kumar gibi durur", e: [-4, 0, -6, 5], rel: { hayri: 1 } },
    R: { t: "Taşlar dağıtılsın", e: [8, -5, 8, -5], rel: { hayri: -1 } } },

  // ── Gazeteci Tuncay
  { id: "ilan", who: "tuncay", konu: "Resmî ilanlar", once: true,
    text: "Belediye ilanlarını Karakavak Postası'na verin başkanım. Vermezseniz manşetimiz hazır: 'Başkan Nerede?'",
    L: { t: "Şantaja boyun eğmem", e: [4, 0, 0, 0], next: ["manset", 1] },
    R: { t: "İlanlar sizde", e: [0, -4, 0, 0], pol: { id: "ilan", ad: "Gazete ilan bedeli", e: [0, -1, 0, 0], ay: 8 } } },
  { id: "manset", who: "tuncay", konu: "Manşet", chain: true, norel: true,
    text: "Bugünkü manşet: 'BAŞKAN CUMARTESİ MAKAMDA YOKTU!' Siz pazardaydınız ama o kısmı yazmadık.",
    L: { t: "Tekzip gönderin", e: [-4, -3, 0, 0] },
    R: { t: "Aldırmayın", e: [-10, 0, 0, 0] } },
  { id: "horlama", who: "tuncay", konu: "Meclis yayını", chain: true,
    text: "Canlı yayında meclis üyesi Hilmi Bey'in horlaması 400 bin izlendi başkanım. Remiksi bile çıktı.",
    L: { t: "Yayını kesin", e: [-8, 0, 0, 3], rel: { nermin: -1 } },
    R: { t: "Reyting reytingdir", e: [10, 0, 3, -6] } },
  { id: "bisiklet", who: "tuncay", konu: "Gündem", chain: true,
    text: "'Karakavak Belediye Başkanı işe bisikletle gidiyor!' haberimiz ulusal basına düştü. Kamera ekibi kapıda.",
    L: { t: "Kamerasız olmaz mı?", e: [3, 0, 0, 0] },
    R: { t: "Pedallara!", e: [10, 0, 3, 5] } },
  { id: "dizi2", who: "tuncay", konu: "Dizi yayında", chain: true, norel: true,
    text: "Dizi yayında başkanım! Ama ilçeyi mafya yuvası, başkanı da 'kavun baronu' diye göstermişler.",
    L: { t: "Dava açalım", e: [5, -5, 0, 0] },
    R: { t: "Reklamın kötüsü olmaz", e: [-6, 0, 12, 0] } },
  { id: "devkavun2", who: "tuncay", konu: "Uluslararası basın", chain: true, norel: true,
    text: "Dev kavun heykelimiz 'dünyanın en tuhaf heykelleri' listesine girdi başkanım! Turist akını başladı.",
    L: { t: "Utanç verici, kaldırın", e: [-5, -5, 0, 5] },
    R: { t: "Selfie noktası yapın", e: [8, 5, 10, 0] } },
  { id: "sahtehaber", who: "tuncay", konu: "Söylenti",
    text: "Sosyal medyada 'belediye şebeke suyuna ilaç katıyor' diye bir paylaşım yayıldı. Açıklama yapacak mısınız?",
    L: { t: "Ciddiye almayın", e: [-8, 0, 0, 0] },
    R: { t: "Canlı yayında içeceğim", e: [8, 0, 0, 3] } },
  { id: "anket", who: "tuncay", konu: "Anket", pre: true, cd: 40,
    text: "Karakavak Postası anketi: 'Başkanı hangi hayvana benzetiyorsunuz?' Birinci çıkan cevabı söylemeyeyim; siz bir demeç verin.",
    L: { t: "Demeç yok", e: [-4, 0, 0, 0] },
    R: { t: "'Aslan gibiyiz'", e: [6, 0, 0, -4] } },
  { id: "tuncay_dost", who: "tuncay", konu: "Röportaj", relMin: { tuncay: 2 }, cd: 30, w: 2,
    text: "Başkanım, yarınki manşet: 'KARAKAVAK'IN GURURU'. Bir de röportaj verirseniz tam olur.",
    L: { t: "Röportaj yok", e: [4, 0, 0, 0] },
    R: { t: "Buyurun", e: [9, 0, 0, 0] } },
  { id: "tuncay_kus", who: "tuncay", konu: "Dosya", relMax: { tuncay: -2 }, cd: 30, w: 2,
    text: "Başkanım, dosyanız hazır: 'Makamda Kaç Bardak Çay İçildi?' Yarın yayında. İlan verirseniz başka dosyaya geçeriz.",
    L: { t: "Bas bakalım", e: [-10, 0, 0, 0] },
    R: { t: "İlanlar sizin", e: [0, -8, 0, 0], rel: { tuncay: 1 } } },

  // ── Elif Öğretmen ve Çocuk Başkan
  { id: "cocukbaskan", who: "elif", konu: "23 Nisan", months: [3], w: 6, cd: 12,
    text: "23 Nisan'da öğrencilerimiz bir günlüğüne makam koltuğuna oturmak istiyor. Seçimi Ayşe kazandı; çok kararlı bir çocuk.",
    L: { t: "Makam ciddi iştir", e: [-10, 0, 0, -3] },
    R: { t: "Buyursunlar", e: [8, 0, 0, 5], next: ["ayse", 0] } },
  { id: "ayse", who: "ayse", konu: "Çocuk Başkan kararnamesi", chain: true,
    text: "İlk kararım: her mahalleye lunapark, cuma günleri okullar tatil, ıspanak yasak. İmzalayacak mısınız?",
    L: { t: "Veto!", e: [-5, 0, 0, 0] },
    R: { t: "Lunapark hakkımız!", e: [12, -12, 5, -5], rel: { elif: -1 } } },
  { id: "kalorifer", who: "elif", konu: "Okul ısınması", months: [10, 11, 0, 1], cd: 24,
    text: "Okulun kalorifer kazanı bozuldu, çocuklar montla ders işliyor. Millî Eğitim 'bütçe yok' diyor.",
    L: { t: "Millî Eğitim'in işi", e: [-10, 0, 0, 5] },
    R: { t: "Belediye tamir etsin", e: [10, -10, 0, -3] } },
  { id: "fabrikatoz", who: "elif", konu: "Hava kirliliği", chain: true,
    text: "Çocuklar teneffüste öksürmekten top oynayamıyor başkanım. Çimento fabrikasının filtresi çalışmıyor.",
    L: { t: "Biraz toz kuvvettir", e: [-18, 0, 5, 5], rel: { levent: 1 } },
    R: { t: "Filtre takılsın", e: [10, -3, 0, -8], rel: { levent: -1 } } },

  // ── Dursun Ağa
  { id: "sulama", who: "dursun", konu: "Sulama kanalı",
    text: "Köylerin sulama kanalı çöktü başkanım. Tarlalar kurursa bu sene pazarda domates değil, dert satarız.",
    L: { t: "DSİ'ye yazın", e: [-10, 0, -3, 5] },
    R: { t: "Belediye yapsın", e: [10, -12, 5, 0] } },
  { id: "esek", who: "dursun", konu: "Bağış", once: true,
    text: "Köyden belediyeye bir eşek bağışladık: Karaca. Dar sokaklarda çöp toplasın; benzin yemez, arıza yapmaz.",
    L: { t: "Sağ olun, gerek yok", e: [-5, 0, 0, 0] },
    R: { t: "Karaca işe başlasın", e: [8, 5, 0, -5], set: "karaca", next: ["karaca", 5] } },
  { id: "dugunsalonu", who: "dursun", konu: "Düğün salonu",
    text: "Köyde düğün salonu yok, düğünler tarlada oluyor. Geçen hafta davul çalınca inekler kaçtı.",
    L: { t: "Tarla romantiktir", e: [-6, 0, 0, 0] },
    R: { t: "Salon yapılsın", e: [10, -10, 5, 0] } },
  { id: "aracisiz", who: "dursun", konu: "Üretici pazarı",
    text: "Tüccar domatesi bizden beş liraya alıp pazarda elli liraya satıyor. Aracısız üretici pazarı kuralım!",
    L: { t: "Tüccar da esnaftır", e: [-8, 0, 8, 0], rel: { bekir: 1 } },
    R: { t: "Tarladan sofraya", e: [10, -5, -10, 0], rel: { bekir: -1 } } },
  { id: "kavunihracat", who: "dursun", konu: "Kavun ihracatı", fav: "L",
    text: "Kavunlarımıza Körfez'den alıcı çıktı başkanım! Belediye aracılık ederse ufak bir komisyon da kasaya kalır.",
    L: { t: "Kazanç köylünün", e: [6, 0, 3, 0] },
    R: { t: "Komisyon alalım", e: [-4, 10, 4, 0] } },

  // ── Müteahhit Cengiz Bey
  { id: "towers", who: "cengiz", konu: "İmar talebi", once: true,
    text: "Başkanım, dere kenarına 20 katlı 'Karakavak Towers'. Havuzlu, AVM'li. Size de bir daire, laf aramızda.",
    L: { t: "Kapı orada", e: [5, 0, -5, -4], next: ["towersL", 6] },
    R: { t: "Projeyi görelim", e: [-3, 20, 8, 0], set: "towers", next: ["skandal", 4] } },
  { id: "towersL", who: "cengiz", konu: "İkinci teklif", chain: true,
    text: "Projeyi komşu ilçeye yaptık başkanım. Sizin halk manzarasını seyrediyor, vergisini onlar alıyor. İkinci etap sizde olsun mu?",
    L: { t: "Dere bizim", e: [4, 0, 0, 0] },
    R: { t: "Bu sefer olsun", e: [-3, 14, 5, 0], set: "towers", next: ["skandal", 4] } },
  { id: "ihale", who: "cengiz", konu: "Meydan ihalesi",
    text: "Meydan düzenleme ihalesine teklif verdik. Fiyatımız biraz yüksek ama kalitemiz de, ilişkilerimiz de yüksek.",
    L: { t: "En düşük teklif kazanır", e: [5, 5, -5, -6], rel: { nermin: 1 } },
    R: { t: "İlişki önemlidir", e: [-10, -10, 5, 10], rel: { nermin: -1 } } },

  // ── Hatice Abla ve Fatma Teyze
  { id: "kooperatif", who: "hatice", konu: "Pazar tezgâhı", once: true,
    text: "Kooperatifimiz erişte, tarhana, salça yapıyor. Pazarda bize bir tezgâh verin başkanım, kadınlar kendi parasını kazansın.",
    L: { t: "Esnaf kızar", e: [-10, 0, 5, 0], next: ["kooperatifL", 4] },
    R: { t: "En güzel yer sizin", e: [10, 0, -6, 0], rel: { bekir: -1 }, next: ["tarhana", 7] } },
  { id: "kooperatifL", who: "hatice", konu: "İnternet satışı", chain: true,
    text: "Pazarda yer vermediniz; kadınlar ürünü internetten satmaya başladı. Ama kargo parası belimizi büküyor başkanım.",
    L: { t: "Kendi işleri", e: [-6, 0, 3, 0] },
    R: { t: "Belediye kargo desteği", e: [8, -6, 0, 0] } },
  { id: "tarhana", who: "hatice", konu: "Müjde", chain: true, fav: "L",
    text: "Tarhanamız İstanbul'da bir zincir markete girdi! Kooperatif belediyeye kâr payı önerdi başkanım.",
    L: { t: "Sizin hakkınız", e: [10, 0, 0, 0] },
    R: { t: "Kasa sevinir", e: [-3, 12, 0, 0] } },
  { id: "hatice_dost", who: "hatice", konu: "Gönüllüler", relMin: { hatice: 2 }, cd: 30, w: 2,
    text: "Kooperatifin kadınları size gönüllü çalışmak istiyor başkanım. Kapı kapı dolaşırız, çayımız da yanımızda.",
    L: { t: "Gerek yok", e: [-2, 0, 0, 0] },
    R: { t: "Başımızın üstünde", e: [8, -2, 0, 0] } },
  { id: "emekliulasim", who: "fatma", konu: "Ulaşım talebi", not: ["emekliDone"],
    text: "Emekliye otobüs bedava olsun başkanım. Maaş pazara yetmiyor, bir de bilet mi alalım?",
    L: { t: "Kasa ağlar", e: [-8, 4, 0, 0] },
    R: { t: "Emekliye bedava", e: [12, -3, 0, 0], set: "emekliDone", pol: { id: "emekli", ad: "Emekliye bedava ulaşım", e: [0, -1, 0, 0] } } },
  { id: "cukur", who: "fatma", konu: "Çukur",
    text: "Kapımın önündeki çukura üç kere düştüm oğlum... kızım... başkanım! Dördüncüde doğruca makamına gelirim.",
    L: { t: "Uyarı tabelası koyun", e: [-5, -1, 0, 0] },
    R: { t: "Çukur kapansın", e: [5, -3, 0, 0], rel: { kemal: 1 } } },

  // ── Gençler
  { id: "kutuphane", who: "deniz", konu: "Kütüphane",
    text: "Sınav dönemi başkanım. Gece de açık bir kütüphane istiyoruz; evde çalışamıyoruz, kahvede okey sesi var.",
    L: { t: "Kahve de bir okul", e: [-8, 0, 5, 0] },
    R: { t: "Yedi yirmi dört açılsın", e: [10, -4, 0, 3], pol: { id: "kutuphane", ad: "Gece kütüphanesi", e: [0, -1, 0, 0], ay: 6 } } },
  { id: "otobus", who: "deniz", konu: "Ulaşım",
    text: "Kampüse otobüs saatte bir kalkıyor, o da dolu. Öğrenciler otostopla derse gidiyor.",
    L: { t: "Yürümek sağlıktır", e: [-10, 0, 0, 0] },
    R: { t: "Sefer artırılsın", e: [10, -10, 3, 0] } },
  { id: "wifi", who: "deniz", konu: "Ücretsiz internet",
    text: "Meydana ücretsiz internet koyalım! Şifreyi de herkes bilsin: karakavak123.",
    L: { t: "Kitap okuyun", e: [-6, 0, 0, 0] },
    R: { t: "Bağlanın gençler", e: [8, -5, 3, 0] } },
  { id: "bisikletyolu", who: "deniz", konu: "Bisiklet yolu",
    text: "Bisiklet yolu yapalım başkanım. İlçede bisikletli sayısı on dört; ama yol olursa artar, söz.",
    L: { t: "On dört kişi için mi?", e: [-4, 0, 4, 0] },
    R: { t: "Pedal çevirelim", e: [6, -8, -4, 4] } },

  // ── Veteriner Selin
  { id: "barinak", who: "selin", konu: "Sokak hayvanları",
    text: "Sokak köpekleri için barınak, kısırlaştırma ve aşı kampanyası şart başkanım. Mama bağışını biz toplarız.",
    L: { t: "Ankara karar versin", e: [-6, 0, 0, 5] },
    R: { t: "Barınak yapılsın", e: [8, -5, 0, 0], pol: { id: "barinak", ad: "Barınak giderleri", e: [0, -1, 0, 0], ay: 6 } } },
  { id: "karaca", who: "selin", konu: "Hayvan hakları", chain: true,
    text: "Eşek Karaca'nın mesai saatleri hayvan haklarına aykırı başkanım. Üstelik sendikası da yok. Emekli edelim.",
    L: { t: "Karaca çalışkandır", e: [-5, 3, 0, 0], rel: { dursun: 1 } },
    R: { t: "Karaca emekli", e: [8, -3, 0, 0], clr: "karaca" } },

  // ── Kaan Bey
  { id: "avm", who: "kaan", konu: "Yatırım teklifi", once: true,
    text: "Karakavak'a AVM! Sinema, yürüyen merdiven, üçüncü dalga kahveci. Esnafa da yer var tabii, bodrum katta.",
    L: { t: "Çarşımız yeter", e: [-5, 0, 12, -4], rel: { bekir: 1 }, next: ["avmL", 6] },
    R: { t: "Yürüyen merdiven!", e: [12, 5, -12, 5], rel: { bekir: -2 }, pol: { id: "avm", ad: "AVM rekabeti", e: [0, 0, -1, 0], ay: 12 } } },
  { id: "avmL", who: "bekir", konu: "Teşekkür", chain: true,
    text: "AVM komşu ilçeye açıldı başkanım; ama çarşı size minnettar. İndirim haftası yapıyoruz, belediye de bir afiş assa?",
    L: { t: "Afiş sizden", e: [0, 0, 3, 0] },
    R: { t: "Belediye destek versin", e: [4, -5, 8, 0] } },
  { id: "dizi", who: "kaan", konu: "Dizi çekimi", once: true,
    text: "Bir yapım şirketi Karakavak'ta dizi çekmek istiyor: 'Kavunlar da Ağlar'. Ana karakter bir belediye başkanı!",
    L: { t: "Bize set lazım değil", e: [0, 0, -6, 0] },
    R: { t: "Kamera, motor!", e: [8, 8, 8, 0], next: ["dizi2", 4] } },
  { id: "ruzgar", who: "kaan", konu: "Enerji yatırımı", once: true,
    text: "Tepelere rüzgâr türbini dikelim. Kira belediyeye, elektrik ülkeye. Manzara biraz değişir ama modern görünür.",
    L: { t: "Tepeler bizim", e: [6, 0, 0, -6] },
    R: { t: "Pervaneler dönsün", e: [-6, 4, 0, 5], pol: { id: "ruzgar", ad: "Rüzgâr türbini kirası", e: [0, 1, 0, 0], ay: 20 } } },
  { id: "pano", who: "kaan", konu: "Reklam panosu",
    text: "Meydana dev bir LED reklam panosu dikelim başkanım. Kira belediyeye; gece de ışığıyla meydanı aydınlatır.",
    L: { t: "Meydan reklamsız kalsın", e: [5, 0, -4, 0] },
    R: { t: "Pano dikilsin", e: [-5, 4, 4, 0], pol: { id: "pano", ad: "LED pano kirası", e: [0, 1, 0, 0], ay: 18 } } },

  // ── Kayınvalide Naciye Hanım
  { id: "lamba", who: "naciye", konu: "Sokak lambası", once: true,
    text: "Evladım, benim sokağın lambası bir aydır yanmıyor. Belediye başkanı bizim aileden, lamba yanmıyor; el âlem ne der?",
    L: { t: "Sıra herkes için sıra", e: [5, 0, 0, 0], next: ["dolma", 1] },
    R: { t: "Ekip hemen çıksın", e: [-4, -2, 0, 0], next: ["torpil", 3] } },
  { id: "dolma", who: "naciye", konu: "Aile meselesi", chain: true,
    text: "Bayramda size gelmeyeceğim. Bir de bu sene dolma yapmayacağım. Bunu da bil evladım.",
    L: { t: "Adalet her şeyden önce", e: [5, 0, 0, 0] },
    R: { t: "Lamba yandı anneciğim!", e: [-6, -2, 0, 0] } },
  { id: "horoz", who: "naciye", konu: "Şikâyet",
    text: "Komşunun horozu sabah dörtte ötüyor evladım. Zabıta mı gönderirsin, yoksa ben mi hallederim?",
    L: { t: "Horoz doğal alarmdır", e: [-4, 0, 0, 0] },
    R: { t: "Zabıta konuşsun", e: [4, -2, 0, 0] } },

  // ── Ferhat Usta
  { id: "sanayi", who: "ferhat", konu: "Sanayi yolu",
    text: "Sanayi sitesinin yolu çamur deryası usta... pardon başkanım. Müşteri arabasını tamire getirirken bozuyor.",
    L: { t: "Önce mahalleler", e: [5, 0, -10, 0] },
    R: { t: "Yol yapılsın", e: [-5, -10, 15, 0] } },
  { id: "balata", who: "ferhat", konu: "Makam aracı", not: ["bisiklet"], norel: true,
    text: "Makam aracınızın balataları bitmiş başkanım. Orijinal parça üç hafta; çıkma parça yarın, komşu ilçenin eski makam aracından.",
    L: { t: "Orijinal olsun", e: [0, -8, 5, 0] },
    R: { t: "Çıkma olsun", e: [-3, -2, 3, -5] } },

  // ── Hans Bey
  { id: "otel", who: "hans", konu: "Turizm", once: true,
    text: "Sayın Başkan, taş evleri restore edelim, butik otel olsun! Almanya'dan otobüs otobüs emekli getiririm. Wunderbar olur.",
    L: { t: "Evlerimiz bize yeter", e: [0, 0, -6, 0], next: ["pansiyon", 8] },
    R: { t: "Wunderbar!", e: [0, -10, 6, 0], next: ["schnitzel", 5], pol: { id: "turizm", ad: "Turizm sezonu", e: [0, 0, 1, 0], ay: 14 } } },
  { id: "pansiyon", who: "hans", konu: "Ruhsat başvurusu", chain: true,
    text: "Sayın Başkan, kendi pansiyonumu açtım! Menüde 'Karakavak kahvaltısı' var, sucuklu yumurta dâhil. Ruhsat verir misiniz?",
    L: { t: "Yönetmeliğe uymuyor", e: [0, 3, -5, 0] },
    R: { t: "Hayırlı olsun", e: [3, 2, 6, 0] } },
  { id: "mozaik2", who: "hans", konu: "Müze", chain: true,
    text: "Mozaik halka açıldı ve ilk ziyaretçi benim, Sayın Başkan! Esnaf şimdiden 'mozaikli dürüm' satıyor. Bir de bilet koysak?",
    L: { t: "Tarih herkesin", e: [8, 0, 5, 0] },
    R: { t: "Bilet koyun", e: [-4, 4, 0, 0], pol: { id: "muze", ad: "Müze bilet geliri", e: [0, 1, 0, 0], ay: 16 } } },

  // ── Orhan Hoca
  { id: "tribun", who: "orhan", konu: "Stadyum", once: true,
    text: "Karakavakspor üst lige çıktı başkanım! Stadın tribünü yok, taraftar maçları ağaca tırmanıp izliyor.",
    L: { t: "Futbol lükstür", e: [-8, 5, -5, 0], next: ["kume", 6] },
    R: { t: "Tribün yapılsın", e: [4, -8, 3, 0], next: ["deplasman", 7], pol: { id: "tribun", ad: "Tribün inşaatı", e: [0, -1, 0, 0], ay: 4, done: [8, 0, 3, 0], msg: "Tribün açıldı! Taraftar ağaçlardan indi." } } },
  { id: "kume", who: "orhan", konu: "Küme düşme", chain: true,
    text: "Karakavakspor küme düştü başkanım. Taraftar 'tribün olsaydı moral bozulmazdı' diye belediyeye yürüyor.",
    L: { t: "Futbol hâlâ lüks", e: [-10, 0, -3, 0] },
    R: { t: "Seneye tribün sözü", e: [5, -5, 0, 0] } },
  { id: "deplasman", who: "orhan", konu: "Disiplin cezası", chain: true,
    text: "Deplasmanda taraftarımız hakemi kovaladı. Federasyon cezayı kesti, kulüp 'belediye ödesin' diyor.",
    L: { t: "Ödemeyiz", e: [-8, 0, 0, -5] },
    R: { t: "Ödeyelim", e: [5, -10, 0, 0] } },

  // ── Levent Bey
  { id: "fabrika", who: "levent", konu: "Kapasite artışı", once: true,
    text: "Çimento fabrikasına kapasite artışı izni verin başkanım. İki yüz kişiye iş, ilçeye vergi!",
    L: { t: "Toz duman istemeyiz", e: [5, 0, -5, -10], next: ["fabrikaL", 5] },
    R: { t: "Bacalar tütsün", e: [5, 4, 5, 5], next: ["fabrikatoz", 4], pol: { id: "baca", ad: "Fabrika vergisi", e: [0, 1, 0, 0], ay: 16 } } },
  { id: "fabrikaL", who: "levent", konu: "Taşınma kararı", chain: true,
    text: "Fabrika komşu ilçeye taşınıyor başkanım. Yüz kişi işsiz kalacak; kararınız bu mu?",
    L: { t: "Güle güle", e: [-10, 0, -5, -3] },
    R: { t: "Vergi indirimiyle kalın", e: [5, -10, 3, 3] } },

  // ── Norveç heyeti
  { id: "norvec", who: "ingrid", konu: "Heyet ziyareti", chain: true,
    text: "Karakavak'a bayıldık! En çok da kokoreçe. Norveç'e kokoreç ithal etmek istiyoruz. Tarifi paylaşır mısınız?",
    L: { t: "Tarif ata yadigârı", e: [5, 0, 5, 0] },
    R: { t: "İhracat başlasın", e: [0, 10, 8, 5] } },

  // ── Tekir
  { id: "tekir", who: "tekir", konu: "Miyav", cd: 12, w: 0.9, norel: true,
    text: "(Belediye binasının kapısında bir tekir oturuyor. Önce size, sonra boş mama kabına bakıyor.) Miyav.",
    L: { t: "Pisst, git!", e: [0, 0, 0, 0] },
    R: { t: "Mama koyun", e: [2, -1, 0, 0], inc: "tekir" } },

  // ── Fikret
  { id: "festival", who: "fikret", konu: "Kavun Festivali", months: [6, 7], w: 6, cd: 10,
    text: "Başkanım, geleneksel Karakavak Kavun Festivali geldi çattı. Konsere kimi çağıralım?",
    L: { t: "Yerel saz ekibi", e: [3, 2, 5, 0] },
    R: { t: "Ünlü arabeskçi", e: [12, -15, 8, 0] } },
  { id: "devkavun", who: "fikret", konu: "Kent estetiği", once: true,
    text: "Meydana dev bir kavun heykeli dikelim başkanım. Dört metre, altın yaldızlı. İlçenin simgesi olur.",
    L: { t: "Saçmalama Fikret", e: [0, 0, 0, 0] },
    R: { t: "Dev kavun!", e: [3, -10, 5, -4], next: ["devkavun2", 5] } },
  { id: "dolandirici", who: "fikret", konu: "Şüpheli arama", once: true,
    text: "Telefonda biri 'Ankara'dan arıyorum, ödeneğiniz çıktı, önce şu hesaba 50 bin yatırın' diyor. Sesi pek Ankaralı değil başkanım.",
    L: { t: "Kapat, savcılığa bildir", e: [3, 0, 0, 5] },
    R: { t: "Ankara'ysa yatıralım", e: [-5, -15, 0, -5] } },
  { id: "dugun", who: "fikret", konu: "Davetiye", once: true, minM: 12,
    text: "Başkanım, ben evleniyorum! Bütün ilçe davetli. Bir de... halayın başını siz çeker misiniz?",
    L: { t: "İşim çok Fikret", e: [-6, 0, 0, 0] },
    R: { t: "Mendil bende!", e: [10, 0, 5, 0] } },
  { id: "cesme", who: "fikret", konu: "Açılış töreni", pre: true, cd: 40,
    text: "Başkanım, açılışı yapılacak bir şey kalmadı. Geçen yıl açtığımız çeşmeyi bir daha açsak? Kurdele hazır.",
    L: { t: "Ayıp olur", e: [0, 0, 0, 0] },
    R: { t: "Kurdeleyi getir", e: [8, -5, 0, 5] } },
];

// ─── Kriz kartları: bir gösterge uca yaklaşınca Fikret can simidi getirir ─
// İki seçenek de göstergeyi merkeze çeker; fark bedelde.
const CRISES = {
  k0: { who: "sevim", konu: "Kasa alarmı",
    text: "Başkanım, kasada iki aylık maaş kalmadı. Bir çıkış yolu bulmazsak icra kapıya dayanır.",
    L: { t: "Ankara'dan avans", e: [0, 16, 0, -10] },
    R: { t: "Belediye arsası satılsın", e: [-8, 18, 3, 0] } },
  k100: { who: "sevim", konu: "Müfettiş uyarısı",
    text: "Kasa fazla dolu başkanım; Sayıştay 'bu para neden harcanmıyor' diye yazı gönderdi. Bir yatırım lazım.",
    L: { t: "Mahallelere dağıtın", e: [10, -18, 3, 0] },
    R: { t: "Esnafa destek paketi", e: [0, -18, 10, 0] } },
  h0: { who: "fikret", konu: "Halk öfkeli",
    text: "Başkanım, kahvelerde adınız kötüye çıktı. Tencere tava sesi yaklaşıyor; hemen bir şey yapmalıyız.",
    L: { t: "Meydanda halk buluşması", e: [14, -8, 0, 0] },
    R: { t: "Bir ay su bedava", e: [16, -14, 0, -3] } },
  e0: { who: "bekir", konu: "Kepenk uyarısı",
    text: "Çarşı kepenk indirmeye hazırlanıyor başkanım. Son kez kapınızı çalıyoruz.",
    L: { t: "Harç affı", e: [0, -12, 15, 0] },
    R: { t: "Çarşı festivali", e: [3, -10, 13, 0] } },
  e100: { who: "rahmi", konu: "Esnaf sultası",
    text: "Esnaf odası 'belediye bizim' demeye başladı başkanım. Meclis toplantısını kıraathanede yapalım diyorlar.",
    L: { t: "Denetim başlasın", e: [0, 5, -14, 0] },
    R: { t: "Zabıta sıkı çalışsın", e: [3, 3, -12, 0] } },
  a0: { who: "kaymakam", konu: "Resmî ihtar",
    text: "Ankara belediyeden memnun değil başkanım. Bir sonraki ihtar görevden uzaklaştırma olabilir.",
    L: { t: "Ankara'ya ziyaret", e: [0, -6, 0, 14] },
    R: { t: "Genelgelere tam uyum", e: [-6, 0, 0, 15] } },
  a100: { who: "vekil", konu: "Tayin kokusu",
    text: "Başkanım, Ankara'da adınız çok geçiyor; sizi yukarı almak istiyorlar. İlçeden kopmayın!",
    L: { t: "Ankara'ya mesafe", e: [4, 0, 0, -12] },
    R: { t: "Muhalefetle ortak proje", e: [6, -4, 0, -14] } },
};

// ─── Sonlar ───────────────────────────────────────────────────────────────
const ENDINGS = {
  h0: { who: "huseyin", konu: "Son çay",
    text: "Başkanım, belediyenin önü tencere tava sesinden geçilmiyor. Halk 'istifa' diye bağırıyor. Ben de çay ocağını kapattım, kusura bakmayın.",
    manset: "HALK SABRETMEDİ", spot: "Tencere tava eyleminin ardından başkan binayı arka kapıdan terk etti.", kisa: "Tencere tavayla gitti" },
  h100: { who: "fikret", konu: "Tebrik (!)", legacy: true,
    text: "Halk sizi o kadar sevdi ki meydana heykelinizi diktiler başkanım. Heykel sizden popüler oldu. Bu sabah seçim kurulu heykeli aday kabul etti... ve heykel kazandı.",
    manset: "HEYKEL KAZANDI!", spot: "Karakavak siyasi tarihinde bir ilk: bronz aday, etten kemikten başkanı geride bıraktı.", kisa: "Kendi heykeline yenildi" },
  k0: { who: "sevim", konu: "Haciz tutanağı",
    text: "Kasa sıfır başkanım. İcra memuru geldi; makam koltuğunu, semaveri ve Tekir'in mama kabını haczetti.",
    manset: "BELEDİYEYE HACİZ", spot: "İcra memurları makam koltuğundan sonra kedinin mama kabını da götürdü.", kisa: "İcra kapıya dayandı" },
  k100: { who: "sevim", konu: "Müfettiş raporu",
    text: "Kasada o kadar para birikti ki Sayıştay müfettişleri geldi. 'Bu kadar parayı nasıl harcamadınız?' diye üç ay sorguladılar. Görevden uzaklaştırıldınız.",
    manset: "KASA DOLU, MAKAM BOŞ", spot: "Hiç harcama yapmayan belediye, müfettişlerin radarına takıldı.", kisa: "Sayıştay'a takıldı" },
  e0: { who: "bekir", konu: "Kepenk kararı",
    text: "Çarşı kepenk kapattı başkanım. Kasap et, fırıncı ekmek, kahveci çay vermiyor. Size. Sadece size. Bu şartlarda makam yürümez.",
    manset: "ESNAF BOYKOTU", spot: "Çarşıda kepenkler inince başkan ekmek almak için komşu ilçeye gitmek zorunda kaldı.", kisa: "Çarşı kepenk indirdi" },
  e100: { who: "rahmi", konu: "Devir teslim",
    text: "Esnaf odası belediyeyi fiilen devraldı başkanım. Meclis kararları artık kıraathanede, okey masasında alınıyor. Makam odanız tespihçi dükkânı oldu.",
    manset: "BELEDİYE ÇARŞIYA TAŞINDI", spot: "Meclis toplantıları kıraathaneye, kararlar okey masasına taşındı.", kisa: "Makamı okey masası aldı" },
  a0: { who: "vekil", konu: "Görevden uzaklaştırma",
    text: "Ankara telefonlarınıza çıkmıyor. Ödenekler kesildi, partiden ihraç edildiniz. Kaymakamlıktan son yazı geldi: görevden uzaklaştırma.",
    manset: "ANKARA FİŞİ ÇEKTİ", spot: "Ödenekleri kesilen başkan, Kaymakamlık yazısıyla görevden uzaklaştırıldı.", kisa: "Ankara'dan ihraç" },
  a100: { who: "vekil", konu: "Atama müjdesi",
    text: "Ankara sizi o kadar sevdi ki bir sabah kapınıza araç geldi: 'Bakan yardımcılığınız hayırlı olsun!' Karakavak'ı bir daha ancak bayramlarda gördünüz.",
    manset: "BAŞKAN ANKARA'YA UÇTU", spot: "Karakavak'tan bakan yardımcılığına uzanan hikâye; ilçe başkansız kaldı.", kisa: "Ankara'ya terfi" },
  sandik: { who: "huseyin", konu: "Seçim sonucu",
    text: "Sandıktan %{oy} çıktı başkanım. Yetmedi. Son çayınızı getirdim; bardak bile buğulandı.",
    manset: "SANDIK KONUŞTU", spot: "Karakavak halkı sandıkta değişim dedi; başkan makamı devretti.", kisa: "Sandıkta kaybetti" },
  emekli: { who: "fikret", konu: "Veda",
    text: "Yirmi yıl oldu başkanım. Dört dönem, bin küsur evrak, binlerce bardak çay. Artık makamı gençlere bırakma vakti. Tekir'in torunları bile belediyede kadrolu.",
    manset: "BİR DEVRİN SONU", spot: "Dört dönemlik başkanlık, meydanda çay ve kavun ikramıyla uğurlandı.", kisa: "Dört dönem, onurlu veda" },
};

const INTRO = [
  { id: "intro1", who: "fikret", konu: "Hoş geldiniz",
    text: "Hoş geldiniz başkanım! Ben Fikret, makam şefiniz. Evrak gelir; siz sağa ya da sola kaydırırsınız. Yukarıda dört gösterge var: Halk, Kasa, Esnaf, Ankara.",
    L: { t: "Önce çay", e: [0, 0, 0, 0] },
    R: { t: "Anlat Fikret", e: [0, 0, 0, 0] } },
  { id: "intro2", who: "fikret", konu: "Göstergeler",
    text: "Evrakı sürükleyince oklar çıkar: yukarı ok artar, aşağı ok azalır; üç ok büyük etki demek. Kasa, Esnaf ya da Ankara dibe vursa da tavan yapsa da makam gider. Halk ise ne kadar severse o kadar iyi, yeter ki dibe vurmasın.",
    L: { t: "Zor iş", e: [0, 0, 0, 0] },
    R: { t: "Devam", e: [0, 0, 0, 0] } },
  { id: "intro3", who: "fikret", konu: "Makamın incelikleri",
    text: "Bazı kararlar her ay işler; onları üstte 'Yürürlükte' diye görürsünüz. İnsanlar kararlarınızı unutmaz; dost da düşman da kazanırsınız. Beş yılda bir sandık var; anket aşağıda.",
    L: { t: "Bismillah", e: [0, 0, 0, 0] },
    R: { t: "Başlayalım", e: [0, 0, 0, 0] } },
];

const CAY_LINES = {
  hlo: "Kahvede adınız geçince okey taşları bile susuyor. Halkın gönlünü almak lazım.",
  hhi: "Düğünlerde adınıza halay çekiliyor. Sandık bu hafta kurulsa kazanırız.",
  klo: "Kasa tıngır tıngır. Sevim Hanım hesap makinesini bırakıp tespih çekmeye başladı.",
  khi: "Kasa dolu ama millet 'bu para nerede duruyor' diye sormaya başladı.",
  elo: "Çarşıdan geçerken kepenkler iniyor. Hacı Bekir selamı kesti.",
  ehi: "Esnaf odası sizin adınıza kulis yapıyor. Fazla sevgi de dert.",
  alo: "Ankara'dan telefon gelmiyor. Bayram mesajımızı bile görüldü bıraktılar.",
  ahi: "Ankara sizi çok seviyor. Bu sevgi sizi buradan alıp götürmesin.",
  ok: "Her şey yolunda görünüyor. Böyle sakin zamanlarda ben daha çok korkarım.",
};

const REACT = {
  pos: ["Sağ olun başkanım!", "Eksik olmayın!", "Allah razı olsun.", "Helal olsun size!"],
  neg: ["Peki... Anlaşıldı.", "Bunu unutmam başkanım.", "Hayırlısı diyelim.", "Siz bilirsiniz."],
};

const KULIS = [
  "Makam odasındaki kaktüsün de istifa dilekçesi verdiği konuşuluyor.",
  "Çaycı Hüseyin'in semaveri yeni başkana devretmeden önce parlattığı öğrenildi.",
  "Tekir'in yeni başkanla görüşmeye sıcak baktığı kulislere yansıdı.",
  "Muhtar Rıza kahvede 'ben demiştim' cümlesini bugün on yedi kez kurdu.",
  "Hacı Bekir'in yeni dönemde tabelasını bir metre daha büyüteceği iddia ediliyor.",
  "Emekli Albay Nuri Bey marşın on beşinci kıtasını yazmaya başladı.",
  "Fikret'in masadaki çay bardaklarını hâlâ kaldırmadığı gözlerden kaçmadı.",
];

const QUOTES = [
  "Başkanım iyi insandı, çayını hep tavşan kanı içerdi.",
  "Evrakların çoğunu okudu. Hepsini değil ama çoğunu.",
  "Makam gelir geçer, çay ocağı kalır.",
  "Ben her şeyi not ettim, bir gün kitap yazacağım.",
];
